package:
  name: apasvo
  version: "0.0.7"

source:
  git_url: https://github.com/jemromerol/apasvo
  git_tag: release/v0.0.7

build:
  script: python setup.py install
  entry_points:
    - apasvo = apasvo.apasvo-gui:main
    - apasvo-detector = apasvo.apasvo-detector:main
    - apasvo-generator = apasvo.apasvo-generator:main


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - coverage ==4.0.3
    - matplotlib ==1.5.1
    - nose ==1.3.7
    - numpy ==1.11.0
    - obspy ==1.0.1
    - pyside ==1.2.1
    - python ==2.7.11
    - qt ==4.8.7
    - scipy ==0.17.0
    - setuptools ==20.7.0

  run:
    - coverage ==4.0.3
    - matplotlib ==1.5.1
    - nose ==1.3.7
    - numpy ==1.11.0
    - obspy ==1.0.1
    - pyside ==1.2.1
    - python ==2.7.11
    - qt ==4.8.7
    - scipy ==0.17.0
    - setuptools ==20.7.0


test:
  # Python imports
  imports:
    - apasvo
    - apasvo.gui
    - apasvo.gui.delegates
    - apasvo.gui.models
    - apasvo.gui.views
    - apasvo.gui.views.generated
    - apasvo.picking
    - apasvo.utils
    - apasvo.utils.formats
    - tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

app:
  entry: apasvo
  icon: res/images/app.png
  summary: "APASVO picking tool"
  own_environment: True

about:
  home: https://github.com/jemromerol/apasvo
  license: GNU General Public License v3 (GPLv3)
  summary: 'A graphical tool to perform event detection/picking in seismic traces.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
